name: 'build-action'
description: 'build'
branding:
  icon: 'command'
  color: 'red'
inputs:
  command:
    description: 'build app'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
