name: Linux Container Node Workflow

on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io/nibodocker-dev:${{ github.sha }}
        docker push ${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io/nibodocker-dev:${{ github.sha }} 
  deploy:
    runs-on: ubuntu-latest
    steps:
  
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'nibodocker-dev'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io/nibodocker-dev:${{ github.sha }}'
