name: Linux Container Node Workflow

on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.AZURE_REGISTRY_USERNAME }}:${{ github.sha }}
        docker push ${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.AZURE_REGISTRY_USERNAME }}:${{ github.sha }} 
